// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaxJ2wiszBJK5qg7EuI3f8HReZAsWehbM',
    appId: '1:843787630334:web:79957ea7280d3491ea97af',
    messagingSenderId: '843787630334',
    projectId: 'sss-advising-tu',
    authDomain: 'sss-advising-tu.firebaseapp.com',
    storageBucket: 'sss-advising-tu.firebasestorage.app',
    measurementId: 'G-SG2FYPS8WN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2e4SyjH7LG3ywv46gWHISMntS3n75QPo',
    appId: '1:843787630334:android:bdb59a185231e2a0ea97af',
    messagingSenderId: '843787630334',
    projectId: 'sss-advising-tu',
    storageBucket: 'sss-advising-tu.firebasestorage.app',
  );

  /// خيارات Firebase لتطبيق "CBA Advising" (com.taif.cba.advising) - نفس
  /// مشروع Firebase ونفس قاعدة البيانات تمامًا، بمعرّف تطبيق مختلف فقط.
  static const FirebaseOptions androidAdvising = FirebaseOptions(
    apiKey: 'AIzaSyC2e4SyjH7LG3ywv46gWHISMntS3n75QPo',
    appId: '1:843787630334:android:01b9f5a9d7ea7712ea97af',
    messagingSenderId: '843787630334',
    projectId: 'sss-advising-tu',
    storageBucket: 'sss-advising-tu.firebasestorage.app',
  );

  /// خيارات Firebase لتطبيق "بوابة الإرشاد" الجديد (com.taif.cba.advisingportal)
  /// - نفس مشروع Firebase تمامًا، بمعرّف تطبيق مختلف فقط. سُجِّل فعليًا بـ
  /// Firebase Console (سليمان 2026-08-23) وأُضيف إدخاله إلى
  /// `android/app/google-services.json` بجانب الإدخالين الآخرين.
  static const FirebaseOptions advisingPortal = FirebaseOptions(
    apiKey: 'AIzaSyC2e4SyjH7LG3ywv46gWHISMntS3n75QPo',
    appId: '1:843787630334:android:b13a15e0e42a7b19ea97af',
    messagingSenderId: '843787630334',
    projectId: 'sss-advising-tu',
    storageBucket: 'sss-advising-tu.firebasestorage.app',
  );
}
